//! Status-line-sized worker activity summaries, generated by a lightweight model.
//!
//! A background worker's `:workers` **Task** cell and the escalation banner's
//! task hint both have to answer "what is this worker actually doing?" in ONE
//! line of a real terminal. The durable `task` brief is the wrong text for that
//! job: it is the entire multi-paragraph assignment, so clipping it to the cell
//! width yields the first few words of the *preamble* and says nothing about
//! progress. Every worker in a fan-out that shares a preamble renders as the
//! same indistinguishable row.
//!
//! This module fixes that by generating a short, present-tense **activity
//! summary** with a cheap model ([`SUMMARY_MODEL`], haiku by default) at the two
//! points in a worker's life where the answer changes:
//!
//! 1. **on worker start** — from the task brief, so the row is meaningful before
//!    the first round even finishes;
//! 2. **mid-round, from the live tool-call stream** ([`ActivityTracker`]),
//!    throttled to [`MIDROUND_INTERVAL`]; and
//! 3. **at the end of every round** — from that round's synthesis, so the row
//!    tracks the work instead of freezing at the assignment.
//!
//! ## Why mid-round is the load-bearing one
//!
//! Points 1 and 3 alone are nearly useless in practice, and the reason is
//! visible in the run table: a coordinator does its ENTIRE job in **one round**.
//! Observed on live runs — `turns = 1` with 20–44 tool calls spanning 3–8
//! minutes of wall clock. With refreshes only at round boundaries, the end-of-
//! round refresh therefore fires exactly ONCE, as the run terminates, and for
//! the whole visible lifetime of the worker every surface shows the STARTUP
//! summary. When the brief is short enough that the startup pass can't name
//! anything concrete it emits the [`STARTUP_FALLBACK`] sentinel, which then
//! sticks — producing the reported symptom: a worker burning tool calls for
//! minutes while `:workers` and the escalation banner both read
//! `running · starting up`.
//!
//! [`ActivityTracker`] closes that gap by refreshing from the tool calls as they
//! complete, so the row tracks work at ~30s granularity INSIDE a round.
//!
//! The result is persisted on the run row (`coordinator_runs.activity_summary`)
//! and preferred over `task` by both consuming surfaces.
//!
//! ## Why the budget is derived, not guessed
//!
//! The whole point is to FIT, so the character allowance is computed from the
//! actual render chrome of the consuming surfaces rather than hardcoded to a
//! number that silently drifts away from the code:
//!
//! | surface | chrome | source |
//! |---|---|---|
//! | `:workers` row | [`WORKERS_ROW_CHROME`] | `workers_modal::render` |
//! | escalation head row | [`ESCALATION_HEAD_CHROME`] | `escalation::render` |
//! | escalation status row | [`ESCALATION_STATUS_CHROME`] | `escalation::render` |
//!
//! [`budget`] takes the NARROWEST of the three at the live terminal width — the
//! `:workers` row, which carries the most chrome — and clamps it to
//! [`MIN_BUDGET`]`..=`[`MAX_BUDGET`]. The upper clamp matters as much as the
//! lower one: past ~80 characters a status line stops being glanceable and turns
//! into prose, so a very wide terminal does not buy a rambling summary.
//!
//! Worked example on a 155-column terminal (the width this was tuned against):
//! `min(155-46, 155-26, 155-16) = 109`, clamped to **80**. On a classic 80-column
//! terminal: `min(34, 54, 64) = 34`. Both fit every surface with no mid-word
//! truncation at the render site.
//!
//! Everything decision-shaped here is a pure function with unit tests; the only
//! impure part is the single tool-less [`Backend::complete`] call in
//! [`summarize`].

use crate::backend::{Backend, Msg};
use crate::session::Session;

/// The lightweight model the summarizer prefers. Summarizing one round of work
/// into ~80 characters is a shallow transform — paying frontier-model rates per
/// round for it (on EVERY live worker) is pure waste, so this pins the cheapest
/// capable Claude tier regardless of what the worker itself runs on.
pub const SUMMARY_MODEL: &str = "claude-haiku-4-5";

/// Fixed (non-task) width of a `:workers` modal row.
///
/// Mirrors the format string in `workers_modal::render`:
/// `{gutter:2}{emoji:2}  {id_w}  {st_w+2}  {rt_w}  {task}` — that is 2 (gutter)
/// plus 2 (type glyph) plus 4×2 (separators) plus the three data columns,
/// budgeted at their realistic maxima: id 13 (`w_z1EjHWKA` plus a `↻N` resumed
/// marker), status 12 (`coordinating`), runtime 7 (`1h02m`), giving
/// `12 + 13 + 12 + 7 = 44` — rounded to 46 for the two-space lead-in the header
/// reserves.
pub const WORKERS_ROW_CHROME: usize = 46;

/// Fixed width of the escalation banner's head row.
///
/// Mirrors `escalation::render`: `{glyph:2} escalated → {short:8} · ` — 2 glyph
/// + 13 (` escalated → `) + 8 (`crate::batch::short_id`) + 3 (` · `) = 26.
pub const ESCALATION_HEAD_CHROME: usize = 26;

/// Fixed width of the escalation banner's indented status row.
///
/// Mirrors `escalation::render`: `   ↳ {elapsed} · ` — 3 indent + 2 (`↳ `)
/// + 8 (`1h02m12s` worst case) + 3 (` · `) = 16.
pub const ESCALATION_STATUS_CHROME: usize = 16;

/// Floor for the summary budget. Below this a summary can't carry a verb plus an
/// artifact name, so a very narrow terminal accepts clipping at the render site
/// rather than degrading the summary itself into uselessness.
pub const MIN_BUDGET: usize = 28;

/// Ceiling for the summary budget. A status line longer than this is prose, not
/// a glance — an ultra-wide terminal does not earn a rambling row.
pub const MAX_BUDGET: usize = 80;

/// The character allowance for a summary at `term_width`, derived from the real
/// render chrome of every consuming surface and clamped to
/// [`MIN_BUDGET`]`..=`[`MAX_BUDGET`]. Pure.
///
/// Uses the narrowest surface so ONE stored string fits them all. `usize::MAX`
/// (what `md::term_width` returns for piped output) saturates to the ceiling
/// rather than overflowing.
pub fn budget(term_width: usize) -> usize {
    let narrowest = term_width
        .saturating_sub(WORKERS_ROW_CHROME)
        .min(term_width.saturating_sub(ESCALATION_HEAD_CHROME))
        .min(term_width.saturating_sub(ESCALATION_STATUS_CHROME));
    narrowest.clamp(MIN_BUDGET, MAX_BUDGET)
}

/// [`budget`] at the live terminal width.
pub fn current_budget() -> usize {
    budget(crate::md::term_width())
}

/// How much of the task brief to show the summarizer. The opening of a brief
/// carries the intent; the tail is usually boilerplate, and a cheap model does
/// not need the whole thing to name the work.
const TASK_CONTEXT_MAX: usize = 600;

/// How much of the latest round synthesis to show the summarizer. Generous
/// enough to capture what actually happened in the round.
const RECENT_CONTEXT_MAX: usize = 1200;

/// The sentinel the model emits when nothing concrete has happened yet, mapped
/// to a plain-English starting state rather than an empty cell.
const STARTUP_FALLBACK: &str = "starting up";

/// The summarizer's system prompt, budget-interpolated so the hard limit the
/// model is told matches the limit [`sanitize`] enforces. Pure.
pub fn summarizer_system(budget: usize) -> String {
    format!(
        "You write ONE ultra-short status line describing what a background agent worker is \
doing RIGHT NOW. It renders in a terminal status row, so it must fit.\n\n\
Rules:\n\
- Output ONLY the status line. No prose, no preamble, no quotes, no markdown, no code fences, \
no bullet, no trailing period.\n\
- HARD LIMIT: {budget} characters. Shorter is better — aim for {aim}.\n\
- Present tense, active voice, concrete. Lead with the verb: \"wiring summaries into :workers\", \
\"fixing CI on feat/foo\", \"auditing 12 merged cards\".\n\
- Name the specific artifact — file, module, branch, PR, test, card — whenever you know it.\n\
- Describe the CURRENT step, not the whole assignment.\n\
- No filler. Never \"working on\", \"currently\", \"the task is\", \"the agent is\", \
\"continuing to\".\n\
- If nothing concrete has happened yet, output exactly: {STARTUP_FALLBACK}",
        aim = budget.saturating_sub(budget / 4).max(MIN_BUDGET),
    )
}

/// Assemble the summarizer's user message: the assignment for grounding, then
/// the latest round synthesis when there is one. Pure + deterministic so the
/// prompt shape is unit-testable.
pub fn build_prompt(task: &str, recent: Option<&str>, budget: usize) -> String {
    let mut p = String::with_capacity(TASK_CONTEXT_MAX + RECENT_CONTEXT_MAX + 256);
    p.push_str("ASSIGNMENT (for context — do NOT just restate it):\n");
    p.push_str(&clip_chars(task.trim(), TASK_CONTEXT_MAX));
    match recent.map(str::trim).filter(|r| !r.is_empty()) {
        Some(r) => {
            p.push_str("\n\nMOST RECENT TURN (what just happened — summarize THIS):\n");
            p.push_str(&clip_chars(r, RECENT_CONTEXT_MAX));
            p.push_str("\n\nStatus line describing the worker's current step");
        }
        None => {
            p.push_str(
                "\n\nThe worker is just starting — no turns have completed yet.\n\n\
Status line describing what it is about to begin",
            );
        }
    }
    p.push_str(&format!(" (max {budget} chars):"));
    p
}

/// Turn the model's raw reply into one clean status line within `budget`, or
/// `None` when it returned nothing usable. Strips code fences, bullets, quotes,
/// and a trailing period; collapses whitespace; takes the first meaningful line;
/// then clips on a WORD boundary so a row never ends mid-identifier. Pure.
pub fn sanitize(raw: &str, budget: usize) -> Option<String> {
    let first = raw
        .lines()
        .map(str::trim)
        .find(|l| !l.is_empty() && !l.starts_with("```"))?;
    // Collapse internal whitespace — a status row is strictly one line.
    let mut s: String = first.split_whitespace().collect::<Vec<_>>().join(" ");
    // Strip a leading bullet/sigil the model may have added anyway.
    for p in ["- ", "* ", "• ", "> ", "$ "] {
        if let Some(rest) = s.strip_prefix(p) {
            s = rest.trim().to_string();
            break;
        }
    }
    // Strip symmetric wrapping quotes/backticks.
    for q in ['"', '\'', '`'] {
        if s.len() >= 2 && s.starts_with(q) && s.ends_with(q) {
            s = s[q.len_utf8()..s.len() - q.len_utf8()].trim().to_string();
        }
    }
    // A status line is a fragment, not a sentence — drop a trailing period.
    if let Some(rest) = s.strip_suffix('.')
        && !rest.ends_with('.')
    {
        s = rest.trim_end().to_string();
    }
    if s.is_empty() {
        return None;
    }
    Some(clip_words(&s, budget))
}

/// Clip to at most `max` characters on a word boundary, appending `…` when
/// anything was dropped. Falls back to a hard character clip when the first word
/// alone overruns the budget. Pure.
pub fn clip_words(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    // Reserve one cell for the ellipsis.
    let room = max.saturating_sub(1);
    let mut out = String::new();
    for word in s.split_whitespace() {
        let need = if out.is_empty() {
            word.chars().count()
        } else {
            out.chars().count() + 1 + word.chars().count()
        };
        if need > room {
            break;
        }
        if !out.is_empty() {
            out.push(' ');
        }
        out.push_str(word);
    }
    if out.is_empty() {
        // One pathological long token — hard clip it.
        out = s.chars().take(room).collect();
    }
    out.push('…');
    out
}

/// Hard character clip with no ellipsis, for prompt context trimming. Pure.
fn clip_chars(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        s.to_string()
    } else {
        s.chars().take(max).collect()
    }
}

/// Build a dedicated lightweight backend for summarization, or `None` when no
/// Claude credential is resolvable (an offline / non-Claude run simply skips
/// summaries — the surfaces fall back to the task brief as before).
///
/// A SEPARATE backend rather than `set_model` on the worker's own: mutating the
/// live coordinator backend mid-run to a weaker model, even briefly, risks a
/// concurrent turn landing on the wrong tier.
pub fn lightweight_backend(session: &Session) -> Option<Backend> {
    let cred = crate::backend::claude::Credential::resolve(&session.env).ok()?;
    Backend::new_claude(SUMMARY_MODEL.to_string(), cred).ok()
}

/// Summarize a worker's current activity into one status-line-sized string.
///
/// Issues a SINGLE tool-less [`Backend::complete`] call at the live
/// [`current_budget`]. Best-effort by design: any error, refusal, or unusable
/// reply yields `None` and the caller leaves the previous summary in place —
/// a summarizer hiccup must never fail or stall the worker's real work.
pub async fn summarize(backend: &Backend, task: &str, recent: Option<&str>) -> Option<String> {
    let budget = current_budget();
    let system = summarizer_system(budget);
    let prompt = build_prompt(task, recent, budget);
    let turn = backend
        .complete(&system, &[Msg::user(prompt)], &[])
        .await
        .ok()?;
    sanitize(&turn.text, budget)
}

// ── Mid-round tracker ───────────────────────────────────────────────────────
//
// See the "Why mid-round is the load-bearing one" note at the top of the module:
// rounds are long and there is usually only ONE, so a round-boundary-only
// refresh leaves the row frozen at the startup summary for the worker's entire
// visible life. This tracker refreshes from the tool-call stream instead.

/// Minimum wall-clock spacing between mid-round refreshes. Each refresh is one
/// haiku call, so this is the cost knob: a 10-minute round refreshes ~20 times
/// (fractions of a cent) while still moving the row faster than an operator
/// can get impatient with it.
pub const MIDROUND_INTERVAL: std::time::Duration = std::time::Duration::from_secs(30);

/// Minimum NEW tool calls since the last refresh before another is allowed.
/// Guards the degenerate case of a round that sits in ONE very long tool call
/// (a 20-minute `cargo build`): re-summarizing the same unchanged digest every
/// 30s would spend tokens to rewrite the identical line.
pub const MIDROUND_MIN_CALLS: usize = 2;

/// How many recent tool-call descriptions to carry into the digest. Enough to
/// show a direction of travel (read → edit → test) without turning the prompt
/// into a transcript.
pub const RECENT_CALLS: usize = 6;

/// Whether a mid-round refresh is due. Pure, so the throttle is unit-testable
/// without a clock or a backend.
pub fn should_refresh(since_last: std::time::Duration, new_calls: usize) -> bool {
    new_calls >= MIDROUND_MIN_CALLS && since_last >= MIDROUND_INTERVAL
}

/// Strip the leading display glyph (`🛠️ `/`🔧 `/`🤝 `) off an `engine` tool
/// description, leaving the text a language model should actually read. Pure.
///
/// Drops leading characters until the first printable ASCII one, so it degrades
/// safely if the glyph set ever changes and keeps a leading `./` or `../` on a
/// path; a desc with no glyph is untouched.
pub fn strip_glyph(desc: &str) -> &str {
    match desc.find(|c: char| c.is_ascii_graphic()) {
        Some(i) => &desc[i..],
        None => desc.trim(),
    }
}

/// Render the mid-round tool-call digest the summarizer reads. Pure +
/// deterministic so the prompt shape is unit-testable.
pub fn digest(recent: &[String], total_calls: usize, round: u64) -> String {
    let mut d = String::with_capacity(RECENT_CALLS * 72 + 160);
    d.push_str(&format!(
        "The worker is MID-ROUND (round {round}, {total_calls} tool calls completed so far). \
It has NOT finished. Its most recent tool calls, oldest first:\n"
    ));
    for r in recent {
        d.push_str("- ");
        d.push_str(r);
        d.push('\n');
    }
    d
}

/// Live mid-round summary refresher for a background coordinator run.
///
/// Attached to the [`Session`] by `coordinator::drive` (so it is `Some` only for
/// a headless `--coordinator` run, exactly like `turn_audit` and
/// `worker_transcript`) and driven by `engine::run_turn`, which notes every
/// completed tool call and offers a throttled refresh point.
///
/// Owns the lightweight backend and the store handle, so it is also the single
/// writer for the startup and round-boundary refreshes — one code path, one
/// client, one place where the durable row is stamped.
pub struct ActivityTracker {
    backend: Backend,
    store: crate::coordinator_store::CoordinatorStore,
    run_id: String,
    /// The durable assignment, pre-clipped for prompt grounding.
    task: String,
    /// Rolling window of the last [`RECENT_CALLS`] tool-call descriptions.
    recent: std::collections::VecDeque<String>,
    total_calls: usize,
    calls_since_refresh: usize,
    last_refresh: std::time::Instant,
    round: u64,
}

impl ActivityTracker {
    /// Build a tracker, or `None` when no Claude credential resolves (an
    /// offline / non-Claude run simply has no summaries and every surface falls
    /// back to the task brief, exactly as before — this is cosmetic, never
    /// load-bearing).
    pub fn attach(
        session: &Session,
        store: &crate::coordinator_store::CoordinatorStore,
        run_id: &str,
        task: &str,
    ) -> Option<Self> {
        Some(Self {
            backend: lightweight_backend(session)?,
            store: store.clone(),
            run_id: run_id.to_string(),
            task: clip_chars(task.trim(), TASK_CONTEXT_MAX),
            recent: std::collections::VecDeque::with_capacity(RECENT_CALLS),
            total_calls: 0,
            calls_since_refresh: 0,
            last_refresh: std::time::Instant::now(),
            round: 1,
        })
    }

    /// Record a COMPLETED tool call. Cheap and synchronous — pure bookkeeping,
    /// no I/O, no await — so it is safe to call on every call in the hot loop.
    ///
    /// `desc` is `engine`'s display description (glyph included); the glyph is
    /// stripped here so the prompt carries text rather than decoration.
    pub fn note_tool_call(&mut self, desc: &str, is_error: bool) {
        let line = if is_error {
            format!("failed: {}", strip_glyph(desc))
        } else {
            strip_glyph(desc).to_string()
        };
        if self.recent.len() == RECENT_CALLS {
            self.recent.pop_front();
        }
        self.recent.push_back(clip_chars(&line, 120));
        self.total_calls = self.total_calls.saturating_add(1);
        self.calls_since_refresh = self.calls_since_refresh.saturating_add(1);
    }

    /// Refresh the durable summary from the tool-call stream IF the throttle
    /// allows it. Returns the new summary when one was written.
    ///
    /// Best-effort throughout: a summarizer error leaves the previous summary
    /// in place and the worker's real work proceeds untouched. The throttle
    /// counters are reset on an ATTEMPT, not on success — a persistently failing
    /// summarizer must not turn into a per-tool-call retry storm.
    pub async fn maybe_refresh(&mut self) -> Option<String> {
        if !should_refresh(self.last_refresh.elapsed(), self.calls_since_refresh) {
            return None;
        }
        self.last_refresh = std::time::Instant::now();
        self.calls_since_refresh = 0;
        let recent: Vec<String> = self.recent.iter().cloned().collect();
        let d = digest(&recent, self.total_calls, self.round);
        self.write(summarize(&self.backend, &self.task, Some(&d)).await?)
    }

    /// Seed the summary from the task brief alone, before the first round runs,
    /// so the row is meaningful from the moment the worker appears.
    pub async fn refresh_startup(&mut self) -> Option<String> {
        self.last_refresh = std::time::Instant::now();
        self.calls_since_refresh = 0;
        let task = self.task.clone();
        self.write(summarize(&self.backend, &task, None).await?)
    }

    /// Refresh from a finished round's synthesis — the model's own narrative of
    /// what it just completed, the single best signal available at a boundary.
    /// Also rolls the round counter and clears the tool-call window so the next
    /// round's digest doesn't describe the previous round's work.
    pub async fn refresh_round(&mut self, round: u64, synthesis: &str) -> Option<String> {
        self.last_refresh = std::time::Instant::now();
        self.calls_since_refresh = 0;
        self.recent.clear();
        self.round = round.saturating_add(1);
        let task = self.task.clone();
        self.write(summarize(&self.backend, &task, Some(synthesis)).await?)
    }

    /// Stamp the durable row. Best-effort — a store write error is swallowed.
    fn write(&self, sum: String) -> Option<String> {
        let _ = self.store.set_activity_summary(&self.run_id, &sum);
        Some(sum)
    }
}

// ── Parent-side read path ────────────────────────────────────────────────────
//
// A worker's summary is written by its coordinator SUBPROCESS, so the parent's
// in-memory `WorkerJob` never sees it — the durable row is the only channel. The
// consuming surfaces are PAINT paths (`:workers` render, the footer's escalation
// refresh, which repaints on every heartbeat), so a naive point lookup would put
// SQLite on the repaint path. This read-through cache bounds that to one query
// per worker per [`POLL_INTERVAL`] regardless of repaint rate.
//
// Kept here rather than as a `WorkerJob` field on purpose: it serves BOTH
// surfaces (and durable rows from other sessions, which have no `WorkerJob` at
// all) with one implementation, and it keeps a store handle out of `worker.rs`.

/// Minimum spacing between durable-store polls for the SAME run id. A summary
/// changes at most once per [`MIDROUND_INTERVAL`] (tens of seconds), so a 2s
/// floor is invisible to the operator and makes the repaint path effectively
/// free.
const POLL_INTERVAL: std::time::Duration = std::time::Duration::from_secs(2);

type SummaryCache =
    std::sync::Mutex<std::collections::HashMap<String, (std::time::Instant, Option<String>)>>;

fn cache() -> &'static SummaryCache {
    static CACHE: std::sync::OnceLock<SummaryCache> = std::sync::OnceLock::new();
    CACHE.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()))
}

/// The cached activity summary for `run_id`, refreshed from `store` at most once
/// per [`POLL_INTERVAL`]. `None` when the run has no summary yet (pre-migration
/// row, summarizer disabled, or the first round hasn't landed) — callers then
/// fall back to clipping the task brief.
pub fn cached_summary(
    store: &crate::coordinator_store::CoordinatorStore,
    run_id: &str,
) -> Option<String> {
    let now = std::time::Instant::now();
    let mut guard = cache().lock().unwrap();
    if let Some((at, val)) = guard.get(run_id)
        && now.duration_since(*at) < POLL_INTERVAL
    {
        return val.clone();
    }
    let fresh = store.activity_summary(run_id);
    guard.insert(run_id.to_string(), (now, fresh.clone()));
    fresh
}

/// Drop a run's cached summary — called when a worker is closed so a long-lived
/// session's cache can't grow without bound.
pub fn forget_cached(run_id: &str) {
    cache().lock().unwrap().remove(run_id);
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Mid-round tracker ───────────────────────────────────────────────────
    //
    // The bug these cover: a coordinator does its whole job in ONE round, so a
    // round-boundary-only refresh fires once (at termination) and every surface
    // shows "starting up" for the worker's entire visible life.

    #[test]
    fn throttle_needs_both_time_and_new_calls() {
        use std::time::Duration;
        // Both conditions met -> refresh.
        assert!(should_refresh(MIDROUND_INTERVAL, MIDROUND_MIN_CALLS));
        assert!(should_refresh(Duration::from_secs(600), 40));
        // Enough calls but too soon: a burst of fast reads must not spend a
        // haiku call per read.
        assert!(!should_refresh(
            MIDROUND_INTERVAL - Duration::from_millis(1),
            99
        ));
        // Enough time but no new work: a round parked in ONE 20-minute
        // `cargo build` must not re-summarize an unchanged digest every 30s.
        assert!(!should_refresh(Duration::from_secs(3600), 0));
        assert!(!should_refresh(
            Duration::from_secs(3600),
            MIDROUND_MIN_CALLS - 1
        ));
        // Nothing has happened at all.
        assert!(!should_refresh(Duration::ZERO, 0));
    }

    #[test]
    fn throttle_fires_well_inside_an_observed_round() {
        // Live symptom runs: 3m07s and 5m25s, both still on round 1. At one
        // refresh per MIDROUND_INTERVAL the row moves many times over the span
        // where it previously never moved once.
        let span = std::time::Duration::from_secs(187); // 3m07s
        let refreshes = span.as_secs() / MIDROUND_INTERVAL.as_secs();
        assert!(
            refreshes >= 6,
            "expected the row to move repeatedly inside a single round, got {refreshes}"
        );
    }

    #[test]
    fn strip_glyph_drops_decoration_not_text() {
        // `engine`'s own description prefixes, which carry no meaning for a
        // language model but do eat prompt budget.
        assert_eq!(
            strip_glyph("🛠️ run_program cargo test"),
            "run_program cargo test"
        );
        assert_eq!(
            strip_glyph("🔧 read_file src/lib.rs"),
            "read_file src/lib.rs"
        );
        assert_eq!(strip_glyph("🤝 tell w_abc"), "tell w_abc");
        // Already clean -> untouched.
        assert_eq!(strip_glyph("grep_files foo"), "grep_files foo");
        // Degenerate inputs must not panic or slice mid-codepoint.
        assert_eq!(strip_glyph(""), "");
        assert_eq!(strip_glyph("🛠️"), "🛠️");
        assert_eq!(strip_glyph("  🛠️  x"), "x");
        // Leading ASCII punctuation is text, not decoration: a relative path
        // must survive intact.
        assert_eq!(
            strip_glyph("🛠️ ./scripts/build.sh --release"),
            "./scripts/build.sh --release"
        );
    }

    #[test]
    fn digest_states_the_round_is_unfinished() {
        let recent = vec![
            "read_file src/engine.rs".to_string(),
            "failed: run_program cargo build".to_string(),
        ];
        let d = digest(&recent, 17, 3);
        // Grounding: the summarizer must not narrate this as a finished result.
        assert!(d.contains("MID-ROUND"), "{d}");
        assert!(d.contains("has NOT finished"), "{d}");
        // Progress signal the old round-boundary-only path could never supply.
        assert!(d.contains("round 3"), "{d}");
        assert!(d.contains("17 tool calls"), "{d}");
        // Every recent call is present, and a failure is marked as such.
        assert!(d.contains("read_file src/engine.rs"), "{d}");
        assert!(d.contains("failed: run_program cargo build"), "{d}");
    }

    #[test]
    fn digest_survives_an_empty_window() {
        // First refresh of a round after `refresh_round` cleared the window.
        let d = digest(&[], 0, 1);
        assert!(d.contains("round 1"), "{d}");
        assert!(!d.is_empty());
    }

    #[test]
    fn digest_is_a_plausible_prompt_payload() {
        // The digest goes through `build_prompt`, which clips the recent-turn
        // slot; a full window must stay comfortably inside that budget so no
        // call is silently truncated away.
        let recent: Vec<String> = (0..RECENT_CALLS)
            .map(|i| format!("run_program cargo test --package aish-{i}"))
            .collect();
        let d = digest(&recent, 44, 1);
        assert!(d.len() < RECENT_CONTEXT_MAX, "digest {} chars", d.len());
        for r in &recent {
            assert!(d.contains(r.as_str()), "dropped {r}");
        }
    }

    #[test]
    fn budget_is_derived_from_the_narrowest_surface() {
        // The `:workers` row carries the most chrome, so it binds.
        // 118 - 46 = 72, which is inside the clamp window.
        assert_eq!(budget(118), 72);
        // The other two surfaces would have allowed more.
        const { assert!(118 - ESCALATION_HEAD_CHROME > 72) };
        const { assert!(118 - ESCALATION_STATUS_CHROME > 72) };
    }

    #[test]
    fn budget_at_the_measured_tui_width_is_the_ceiling() {
        // 155 cols (the width this was tuned against): min(109,129,138) = 109,
        // clamped to MAX_BUDGET so a wide terminal doesn't buy prose.
        assert_eq!(budget(155), MAX_BUDGET);
    }

    #[test]
    fn budget_clamps_both_ends() {
        // Classic 80-column terminal: 80 - 46 = 34, inside the window.
        assert_eq!(budget(80), 34);
        // Very narrow / degenerate widths floor at MIN_BUDGET.
        assert_eq!(budget(60), MIN_BUDGET);
        assert_eq!(budget(10), MIN_BUDGET);
        assert_eq!(budget(0), MIN_BUDGET);
        // Piped output reports usize::MAX — must saturate, not overflow.
        assert_eq!(budget(usize::MAX), MAX_BUDGET);
    }

    #[test]
    fn budget_is_monotonic_in_width() {
        let mut prev = 0;
        for w in [0usize, 40, 70, 80, 100, 126, 155, 300] {
            let b = budget(w);
            assert!(b >= prev, "budget({w}) = {b} regressed below {prev}");
            assert!((MIN_BUDGET..=MAX_BUDGET).contains(&b));
            prev = b;
        }
    }

    #[test]
    fn sanitize_takes_one_clean_line() {
        assert_eq!(
            sanitize("wiring summaries into :workers", 80).as_deref(),
            Some("wiring summaries into :workers")
        );
        // whitespace collapsed, first meaningful line wins
        assert_eq!(
            sanitize("  \n\n  fixing   CI on feat/foo  \nstray trailing note", 80).as_deref(),
            Some("fixing CI on feat/foo")
        );
    }

    #[test]
    fn sanitize_strips_fences_bullets_quotes_and_trailing_period() {
        assert_eq!(
            sanitize("```\nauditing 12 merged cards\n```", 80).as_deref(),
            Some("auditing 12 merged cards")
        );
        assert_eq!(
            sanitize("- rebasing feat/bar", 80).as_deref(),
            Some("rebasing feat/bar")
        );
        assert_eq!(
            sanitize("\"opening draft PR\"", 80).as_deref(),
            Some("opening draft PR")
        );
        assert_eq!(
            sanitize("running cargo test.", 80).as_deref(),
            Some("running cargo test")
        );
        // an ellipsis-ish trailing run is left alone
        assert_eq!(
            sanitize("still building..", 80).as_deref(),
            Some("still building..")
        );
    }

    #[test]
    fn sanitize_returns_none_for_nothing_usable() {
        assert_eq!(sanitize("", 80), None);
        assert_eq!(sanitize("   \n\t  ", 80), None);
        assert_eq!(sanitize("```\n```", 80), None);
        assert_eq!(sanitize("\"\"", 80), None);
    }

    #[test]
    fn sanitize_never_exceeds_the_budget() {
        let long = "wiring the lightweight activity summarizer into the coordinator round \
boundary and both status surfaces";
        for b in [MIN_BUDGET, 34, 50, MAX_BUDGET] {
            let got = sanitize(long, b).expect("summary");
            assert!(
                got.chars().count() <= b,
                "budget {b}: {:?} is {} chars",
                got,
                got.chars().count()
            );
        }
    }

    #[test]
    fn clip_words_breaks_on_word_boundaries() {
        let s = "fixing CI on feat/activity-summary";
        // Fits — untouched, no ellipsis.
        assert_eq!(clip_words(s, 80), s);
        // Clipped on a word boundary with an ellipsis.
        let got = clip_words(s, 16);
        assert!(got.ends_with('…'), "{got:?}");
        assert!(!got.contains("feat/activity-summary"), "{got:?}");
        assert!(got.chars().count() <= 16);
    }

    #[test]
    fn clip_words_handles_one_overlong_token() {
        let got = clip_words("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 10);
        assert_eq!(got.chars().count(), 10);
        assert!(got.ends_with('…'));
    }

    #[test]
    fn clip_words_is_char_safe_on_multibyte() {
        // Must not panic slicing inside a multi-byte scalar.
        let got = clip_words("résumé des tâches en cours sur la branche", 12);
        assert!(got.chars().count() <= 12, "{got:?}");
    }

    #[test]
    fn summarizer_system_states_the_budget_it_is_held_to() {
        let s = summarizer_system(34);
        assert!(s.contains("HARD LIMIT: 34 characters"), "{s}");
        assert!(s.contains(STARTUP_FALLBACK), "{s}");
    }

    #[test]
    fn build_prompt_distinguishes_startup_from_a_completed_round() {
        let start = build_prompt("Do the big thing", None, 80);
        assert!(start.contains("just starting"), "{start}");
        assert!(start.contains("Do the big thing"), "{start}");
        assert!(start.contains("max 80 chars"), "{start}");

        let mid = build_prompt("Do the big thing", Some("Added the store column."), 80);
        assert!(mid.contains("MOST RECENT TURN"), "{mid}");
        assert!(mid.contains("Added the store column."), "{mid}");
        assert!(!mid.contains("just starting"), "{mid}");
    }

    #[test]
    fn build_prompt_clips_oversized_context() {
        let huge_task = "t".repeat(5_000);
        let huge_recent = "r".repeat(5_000);
        let p = build_prompt(&huge_task, Some(&huge_recent), 80);
        assert!(
            p.len() < TASK_CONTEXT_MAX + RECENT_CONTEXT_MAX + 512,
            "{}",
            p.len()
        );
    }
}
